id: PA1DBB43F
initial_creation_type: input
source_metadata:
  title: Bhagavadgītā with the commentary ascribed to Śaṃkara (Adhyāyas 1-17)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Gaudiya Grantha Mandira
  contribution to GRETIL: Gaudiya Grantha Mandira
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:56:12.959355'
last_modified_at: '2022-03-09T14:56:12.959369'
